export enum RoutesNavigationViews {
  Home = '',
  How_We_Are = 'quienes-somos',
  Medical_Record = 'ficha-medica',
  Rules = 'reglamento',
  Tournament = 'torneo',
  Division = 'division',
  Stage = 'etapa',
  Match = 'partido',
  Venue = 'cancha',
  Player = 'jugador',
  PlayerSanction = 'sancion',
  Team = 'equipo',
  Teams = 'equipos',
  Scorers = 'goleadores',
  Sanctions = 'sanciones',
}
