<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Compile Remove="NewFolder2\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder2\**" />
    <None Remove="NewFolder1\**" />
    <None Remove="NewFolder2\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Sanction\Sancion.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Division\NewFile1.txt" />
    <None Remove="Match\NewFile1.txt" />
    <None Remove="PlayerStatistic\NewFile1.txt" />
    <None Remove="StandingSummary\NewFile1.txt" />
    <None Remove="SanctionPlayer\NewFile1.txt" />
    <None Remove="Sanction\NewFile1.txt" />
    <None Remove="Statistic\NewFile1.txt" />
    <None Remove="Tournament\NewFile1.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
  </ItemGroup>

</Project>
