const routes = {
  apiUrl: '/api',

  auditLogs: 'audit-logs',
  backups: 'backups',
  clubs: 'clubs',
  blogposts: 'blogposts',
  maintenance: 'maintenance',
  dataMaintenance: 'data-maintenance',
  divisions: 'divisions',
  stages: 'stages',
  matches: 'matches',
  matchSeries: 'match-series',
  medicalRecords: 'medical-records',
  players: 'players',
  seasons: 'seasons',
  scorer: 'scorer',
  playerSanctions: 'player-sanctions',
  playerStatistics: 'player-statistics',
  statistics: 'statistics',
  staff: 'staffs',
  teams: 'teams',
  tournaments: 'tournaments',
  users: 'users',
  auth: 'auth',
  venues: 'venues',
  tokenInvalido: '/token-invalido',
};

export default routes;
